= Kein Story Arc

One snowy day when I was but a boy, I found a mysterious device. Curious, I pressed a button, which activated Hover ability. Unable to master the usage of the device, I was drifted into the sky until the ability's duration ended.

== Explorer Arc

When I landed, I found myself in middle of a city that I had never heard. Moreover, people in the city spoke in the language that I never heard. It took me some time to learn the language and earn a living. My goal is fairly simple: To go back home. (Opening) Once we are through the portal at the bath-house, I saw gold coins. As soon as I got down from the air, I started to shove them into my pocket. Hudson asked why, and I revealed my intention to go back home. The problem was that I did not know from where I came. So, I talked about my plan to earn lots of money, so I can travel and find my home. Something happened while I was being sucked in. The belt mitigated the gravity field, though it malfunctioned. Finally, I found a way home. Would be exciting, but Hudson disappeared into the portal. I learnt a glimpse of my past in the library.

== Develop a Bond Arc

Got shot by Arvid. Pretty mad. (Opening) Apparently, I took Arvid long time ago, and she visits the place frequently.

== Growth Arc
 
Lost Hudson.

