= Kein Story Arc

One snowy day when I was but a boy, I found a mysterious device. Curious, I pressed a button, which activated Hover ability. Unable to master the usage of the device, I was drifted into the sky until the ability's duration ended.

== Background

Long time ago, I fell from the sky near Sunflower Cafe in River Gate district. Hoya was there, eating biscotti. He took interest and pity on me, feeding me the biscotti and taking care of me. Ever since then, I visited the Sunflower Cafe frequently evenever I got nostalgic.

== Explorer Arc

When I landed, I found myself in middle of a city that I had never heard. Moreover, people in the city spoke in the language that I never heard. It took me some time to learn the language and earn a living. My goal is fairly simple: To go back home. (Opening) Once we are through the portal at the bath-house, I saw gold coins. As soon as I got down from the air, I started to shove them into my pocket. Hudson asked why, and I revealed my intention to go back home. The problem was that I did not know from where I came. So, I talked about my plan to earn lots of money, so I can travel and find my home.

Something happened while I was being sucked in. The belt mitigated the gravity field, though it malfunctioned.

Finally, I found a way home. Would be exciting, but Hudson disappeared into the portal. I learnt a glimpse of my past in the library.

In the statue library, I found a book about my potential home.

== Develop a Bond Arc

Got shot by Arvid. Pretty mad. (Opening) Apparently, I took Arvid bath house long time ago, and she visits the place frequently.

Apparantly, Arvid was not one of the leaders of Longerfingers' guild. I got tricked! Also, it seems that every other organization knows of Longfinders' guild. Maybe competing?

I learned that Arvid was kicked out of the guild. And, also, she seemed to like biscotti like me. Perhaps we could be biscotti friend?

== Growth Arc
 
Lost Hudson. (Opening) I was relying on Hudson when I got into trouble. Yet, I could no longer look for helps after he was gone. However, I got a new ability (cognizant offense) and slowly becoming self-reliant, especially I ended the fight with it.

Also, I noticed more reactions in the people like he did.

I tried to be more active like he did. I started to focus in the discussion and be in the zone with the other people. Whether I have done it properly or not? I am not too sure.
